### ISSUE TITLE
Quick question towards the input

### ISSUE THREAD

**Issue by Derekkk** [UKPLab/controlled-argument-generation#4]
Hi, 

Thanks for sharing the code! I have a quick questions about the model inputs: do you use any special token (e.g., [SEP]) to separate the topic, stance, aspects and arguments, or you just simply concat them together? Really appreciate it for your reply. : )

**Comment by v1nc3nt27** [comment]
Hey. No, it's just a whitespace between them and that's it.

**Comment by Derekkk** [comment]
> Hey. No, it's just a whitespace between them and that's it.

Thanks!
