### ISSUE TITLE
Question about training.

### ISSUE THREAD

**Issue by benjpau** [UKPLab/controlled-argument-generation#9]
During training in your paper, did you only train one model on the data across all the topics? Or for every topic, train one model and test on that topic (that is, eight models are trained for the eight topics)? 

If you only trained one model, then how to decide the  --iterations ?

Thanks a lot!

**Comment by v1nc3nt27** [comment]
I trained one model on all common-crawl data (i.e. all topics) and one model on all reddit-comments data. I computed the iterations based on the batch size and the number of training samples such that each training sample was seen once (i.e. basically one epoch).

**Comment by benjpau** [comment]
Thanks for your reply.

For example, if I use "python make_tf_records_multitag.py --files_folder ../training_data/common-crawl-en/abortion/final/ --sequence_len 256" to process the data of abortion, after finish, it says "Number of total samples: 28458."

In this way, for every topic, I can get a number-of-total-samples by running "make_tf_records_multitag.py". So, if I want to train on all the data across all the topics, do I need to sum up all the number-of-total-samples for every topic to compute the iteration number?

By the way, could you please provide the "--iterations" or "batch_size" or "#samples" you used in the experiment of the two models?

Thanks a lot!

**Comment by v1nc3nt27** [comment]
Yes, you sum up all the number of samples and then divide it by the batch size you plan to use. This will be your number of steps (iterations).

Unfortunately, I do not have the iterations explicitly stored somewhere, but if you divide the samples by the batch size you intend to use, you will derive at the same number of iterations I have used.

**Comment by benjpau** [comment]
Thanks a lot!
